// searchAction
export const FETCH_SEARCH_TEXT = 'FETCH_SEARCH_TEXT';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_AMOUNT = 'FETCH_AMOUNT';
export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ORIENTATION = 'FETCH_ORIENTATION';
export const FETCH_IMAGE_TYPE = 'FETCH_IMAGE_TYPE';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_COLOR = 'FETCH_COLOR';
export const FETCH_PAGE = 'FETCH_PAGE';
export const FETCH_MORE_IMAGES_NEXT_PAGE = 'FETCH_MORE_IMAGES_NEXT_PAGE';
export const FETCH_MORE_IMAGES_PREVIOUS_PAGE = 'FETCH_MORE_IMAGES_PREVIOUS_PAGE';
export const WAIT_API_RESPONSE_TYPE_1 = 'WAIT_API_RESPONSE_TYPE_1'; // for 'fetchImages'
export const WAIT_API_RESPONSE_TYPE_2 = 'WAIT_API_RESPONSE_TYPE_2'; // for 'fetchMoreImages'
export const CUT_DOWN_SEARCH_STORE = 'CUT_DOWN_SEARCH_STORE';

// imgViewer
export const VIEWER_LOAD_IMG = 'VIEWER_LOAD_IMG';
export const VIEWER_OPEN = 'VIEWER_OPEN';
export const VIEWER_WAIT_API_RESPONSE = 'VIEWER_WAIT_API_RESPONSE';

// appAdds
export const UPDATE_RECENTLY_WATCHED = 'UPDATE_RECENTLY_WATCHED';
export const WINDOW_TOP = 'WINDOW_TOP';
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export const UPDATE_FAVORITES_ORDER = 'UPDATE_FAVORITES_ORDER';
export const UPDATE_USER_HISTORY = 'UPDATE_USER_HISTORY';
export const WAIT_API_RESPONSE_TYPE_3 = 'WAIT_API_RESPONSE_TYPE_3'; // for 'favorites & recentlyWatched'
export const SET_AUTH_DIALOG_STATUS = 'SET_AUTH_DIALOG_STATUS';